version: '3.5'

services:
  telegram-files-downloader:
    #build: .
    image: clisboa/telegram-files-downloader:latest
    container_name: telegram-files-downloader
    read_only: true
    environment:
      TELEGRAM_DAEMON_API_ID: "YOUR API ID HERE"
      TELEGRAM_DAEMON_API_HASH: "YOUR API HASH HERE"
      TELEGRAM_DAEMON_CHANNEL: "YOUR CHANNEL ID HERE"
      TELEGRAM_DAEMON_BOT_TOKEN: "YOUR BOT TOKEN HERE"
      TELEGRAM_DAEMON_DEST: "/downloads"
    volumes:
       - downloads:/downloads
    restart: unless-stopped

volumes:
    downloads:
